const data = [
    {
        title: "WHAT IS BIG TOYS",
        body:
            "BIG TOYS IS A PROJECT THAT BRINGS YOU THE MOST INCREDIBLE VEHICLES A HUMAN MIND CAN EVER IMAGINE. <br/><br/>" +
            "IN PHASE 1.0, BIG TOYS IS BRINGING THE FAMOUS JUSTICE MOBILE TO LIFE AND GIVING IT AWAY TO A LUCKY WINNER! <br/><br/>" +
            "10000 GENERATIVE JUSTICE MOBILE CARS WITH OVER 170 HAND-DRAWN FEATURES WILL BE AVAILABLE TO MINT… AND ONE LUCKY WINNER WILL TAKE THE IN REAL LIFE JUSTICE MOBILE HOME!"
    }, {
        title: "WHEN IS BIG TOYS GOING TO BE AVAILABLE?",
        body: "BIG TOYS MINT PASS WILL BE AVAILABLE TO MINT ON OCTOBER 10TH AT 2PM ET"+
 "AND THE OFFICIAL BIG TOYS NFT WILL BE AVAILABLE TO MINT ON OCTOBER 17TH AT 2PM ET."
    }, {
        title: "HOW MANY MINT PASSES ARE THERE?",
        body: "A TOTAL OF 10000 MINT PASSES"
    }, {
        title: "HOW MANY BIG TOYS NFTs ARE THERE?",
        body: "A TOTAL OF 10000 TOKENS."
    }, {
        title: "HOW MUCH DOES A MINT PASS COST?",
        body: "0.02 ETH PER MINT PASS."
    }, {
        title: "HOW MUCH DOES A BIG TOYS NFT COST?",
        body: "0.19 ETH PER TOKEN."
    }, {
        title: "HOW MANY MINT PASSES CAN I BUY AT ONCE?",
        body: "97 MINT PASSES PER WALLET."
    }, {
        title: "HOW CAN I MINT THE BIG TOYS NFTs?",
        body: "1 MINT PASS WILL GIVE YOU ACCESS TO MINT 1 BIG TOYS NFT."
    }, {
        title: "HOW ARE YOU GOING TO DO THE GIVEAWAYS?",
        body: "THE GIVEAWAYS WILL BE DONE LIVE ON DISCORD."
    }, {
        title: "WHICH WALLET SHOULD WE USE FOR THE MINT?",
        body: "METAMASK"
    }, {
        title: "I HAVE A MINT PASS. CAN I HAVE ACCESS TO THE GIVEAWAYS WITHOUT MINTING MY BIG TOYS NFT?",
        body: "ONLY BIG TOY NFT HOLDERS WILL HAVE ACCESS TO THE LIST OF GIVEAWAYS."
    }, {
        title: "HOW DO I PURCHASE YOUR NFTs & PASSES?",
        body:
         "IN ORDER TO PURCHASE A BIG TOYS NFT OR OUR MINT PASSES, YOU WILL NEED TO PURCHASE ETH FROM A CRYPTOCURRENCY EXCHANGE LIKE COINBASE OR BINANCE AND TRANSFER THAT ETH INTO A NON-CUSTODIAL DIGITAL WALLET LIKE METAMASK. </br></br>"
         + "HERE IS A STEP-BY-STEP GUIDE TO HELP. <br/>"
         + "1) USE CHROME AS YOUR BROWSER. <br/> "
         + "2) INSTALL METAMASK AS A CHROME EXTENSION AND SET UP YOUR WALLET </br>"
         + "3) CREATE A COINBASE OR BINANCE ACCOUNT AND BUY ETHEREUM. </br>"
         + "4) IN COINBASE OR BINANCE, SEND YOUR ETHEREUM TO YOUR METAMASK WALLET. </br>"
         + "5) HEAD TO WWW.THEREDAPEFAMILY.COM AND MINT THE TRAF NFTS"
    }
];

export default data;
